apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
  labels:
    {{- include "wasp-ingest-mqtt.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  logLevel: {{ .Values.config.logLevel }}
  kafkaLogLevel: {{ .Values.config.kafka.logLevel }}
  mqttEndpoint: {{ include "wasp-ingest-mqtt.mqtt.endpoint" . }}
  kafkaBrokers: {{ include "wasp-ingest-mqtt.kafka.brokers" . }}
  kafkaPayloadTopic: {{ .Values.config.kafka.rawPayloadTopic }}
  waspIngestName: {{ .Values.config.waspIngestName }}
  authHost: {{ .Values.config.waspAuthHost }}
  authPort: {{ .Values.config.waspAuthPort | quote }}
  authRoute: {{ .Values.config.authRoute | quote }}
  apiMajorVersion: {{ .Values.config.apiMajorVersion | quote }}
