apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wasp-ingest-mqtt.fullname" . }}
  labels:
    {{- include "wasp-ingest-mqtt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "wasp-ingest-mqtt.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        name: {{ include "wasp-ingest-mqtt.fullname" . }}
    spec:
      {{- include "wasp-ingest-mqtt.imagePullSecrets" . | indent 6 }}
      {{- include "wasp-ingest-mqtt.initContainers" . | indent 6 }}

      containers:
        - name: {{ include "wasp-ingest-mqtt.fullname" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 5
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: port
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: logLevel
            - name: KAFKA_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: kafkaLogLevel
            - name: MQTT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: mqttEndpoint
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: kafkaBrokers
            - name: KAFKA_PAYLOAD_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: kafkaPayloadTopic
            - name: WASP_INGEST_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: waspIngestName
            - name: AUTH_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: authHost
            - name: AUTH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: authPort
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-secret
                  key: mqttUsername
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-secret
                  key: mqttPassword
            - name: AUTH_ROUTE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: authRoute
            - name: API_MAJOR_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "wasp-ingest-mqtt.fullname" . }}-config
                  key: apiMajorVersion
