apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-ingest-mqtt.fullname" . }}-secret
  labels:
    {{- include "wasp-ingest-mqtt.labels" . | nindent 4 }}
data:
  mqttUsername: {{ .Values.config.mqtt.username | b64enc | quote }}
  mqttPassword: {{ .Values.config.mqtt.password | b64enc | quote }}
