apiVersion: v2
name: wasp-ingest-mqtt
appVersion: '0.0.7'
description: A Helm chart for wasp-ingest-mqtt
version: '0.0.7'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk

dependencies:
  - name: mosquitto-go-auth
    alias: mosquitto
    version: '0.0.2'
    repository: https://digicatapult.github.io/mosquitto-go-auth-helm/
    condition: mosquitto.enabled
  - name: kafka
    version: '12.7.3'
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: nginx
    alias: waspthingmock
    version: '^8.7.1'
    repository: https://charts.bitnami.com/bitnami
    condition: waspthingmock.enabled
