mosquitto:
  enabled: true
  auth:
    hasher: bcrypt
    files:
      passwordEntries: |-
        internal_ingest_mqtt:$2b$10$hgyn8cm/n/FI8kI65cnx5OyqQbrNNBW6OajVwX0Mc9V2N7VrCCaNW
      acls: |-
        user internal_ingest_mqtt
        topic read things/+/messages
waspthingmock:
  enabled: true
  service:
    type: ClusterIP
  serverBlock: |-
    upstream static_backend {
      server localhost:8080;
    }

    server {
      listen 0.0.0.0:8080;
      location /v1/ingest {
        proxy_method GET;

        if ($http_content_type != "application/json") {
            return 415;
        }

        proxy_pass http://static_backend/ingest-mock;
      }
      location /ingest-mock {
        return 201 "{}";
      }
    }

config:
  mqtt:
    username: 'internal_ingest_mqtt'
    password: 'testing123'

image:
  repository: 'wasp-ingest-mqtt'
  tag: 'latest'
  PullPolicy: Never
